version: '3.8'

services:
  inventory-service:
    image: 743008455320.dkr.ecr.ap-southeast-1.amazonaws.com/inventium/inventory-service:1.0.0
    container_name: inventory-service
    ports:
      - "13740:13740"
    networks:
      - inventium
    env_file:
      - app.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13740/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  inventium:
    name: inventium
    external: true
