# In each microservice repo
steps:
  - label: "Load code linter pipeline"
    command: |
      buildkite-agent pipeline upload https://raw.githubusercontent.com/InventiumOrg/buildkite-cicd/main/templates/code-linter.yml

  - label: "Load security scan pipeline"
    command: |
      buildkite-agent pipeline upload https://raw.githubusercontent.com/InventiumOrg/buildkite-cicd/main/templates/security-scan.yml

  - label: "Load image build pipeline"
    command: |
      buildkite-agent pipeline upload https://raw.githubusercontent.com/InventiumOrg/buildkite-cicd/main/templates/image-build.yml