# In each microservice repo
steps:
  - label: ":git: Clone centralized pipeline repo"
    command: |
      git clone --depth 1 https://github.com/InventiumOrg/buildkite-cicd.git /tmp/cicd

  - wait

  - label: ":pipeline: Load code linter pipeline"
    command: |
      ls -la .
      ls -ls /tmp
      ls -la /tmp/cicd
      buildkite-agent pipeline upload templates/code-linter.yml

  - label: ":shield: Load security scan pipeline"
    command: |
      buildkite-agent pipeline upload templates/security-scan.yml

  - label: ":docker: Load image build pipeline"
    command: |
      buildkite-agent pipeline upload templates/image-build.yml
