steps:
  - group: ":golangci-lint: Go Lang Linter"
    key: "golangci-lint"
    steps:
      - label: ""
        command: |
          echo "Running Go Linter...."
          golangci-lint run -v --new-from-rev $BUILDKITE_PULL_REQUEST_BASE_BRANCH

  - group: ":bug: Repository Scan"
    key: "securiy-scan"
    steps:
      - label: ":trivy: Trivy Repository Scan"
        command: |
          echo "Scanning Repo..."
          trivy repo ./
        key: trivy

  - group: ":docker: Multi-Platform Image Build"
    key: "image-build"
    steps:
      - label: ":construction_worker: Build"
        command: echo "Build the rocket"
        key: build

      - label: ":white_check_mark: Test"
        command: echo "Test the rocket"
        key: test
        depends_on: build

      - label: ":rocket: Deploy"
        command: |
          echo "Launch the rocket"
          cat .buildkite/annotation.md | buildkite-agent annotate --style 