// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: inventory.sql

package models

import (
	"context"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (
    name, quantity, category, located
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, quantity, category, located, created_at
`

type CreateInventoryParams struct {
	Name     string
	Quantity int32
	Category string
	Located  string
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory,
		arg.Name,
		arg.Quantity,
		arg.Category,
		arg.Located,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Category,
		&i.Located,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM inventory
WHERE id = $1
`

func (q *Queries) DeleteInventory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInventory, id)
	return err
}
