// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ID        int64
	Name      string
	Quantity  int32
	Category  string
	Located   string
	CreatedAt pgtype.Timestamptz
}
